[env:esp32s3]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
test_build_src = yes

lib_deps = 
	knolleary/PubSubClient@^2.8
	bblanchon/ArduinoJson@^6.21.3
	h2zero/NimBLE-Arduino @ ^1.4.1